# Repository settings for branch protection
# This file can be used with the Probot Settings app (https://github.com/probot/settings)
# or as documentation for manual branch protection configuration

# General repository settings
repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  
  # The name of the repository
  name: Neuro-BRDF
  
  # A short description of the repository that will show up on GitHub
  description: Documentation for Neuro-BRDF reproduction
  
  # Either `true` to make the repository private, or `false` to make it public.
  private: false
  
  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true
  
  # Either `true` to enable projects for this repository, or `false` to disable them.
  has_projects: true
  
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: true

# Branch protection rules
# See https://docs.github.com/en/rest/reference/repos#update-branch-protection for all available settings.
branches:
  - name: main
    # Require at least one approving review on a pull request, before merging.
    protection:
      # Required. Require status checks to pass before merging. Set to null to disable.
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts:
          - "build"
      
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # Specify which users and teams can dismiss pull request reviews.
        dismissal_restrictions:
          users: []
          teams: []
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Require review from Code Owners.
        require_code_owner_reviews: false
        # Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6.
        required_approving_review_count: 1
      
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []
      
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: false
      
      # Required. Require linear history
      required_linear_history: false
      
      # Permit force pushes for all users with push access.
      allow_force_pushes: false
      
      # Allow deletions of the protected branch by users with push access
      allow_deletions: false
